#!/bin/sh
if [ $# -lt 1 ]; then
    echo 'usage: do_cns infile.inp'
    exit 1
fi

if [ ! -f $1 ]; then
   echo 'infile does not exists'
   exit 1
fi
#echo test

touch ${1%.*}.log
cns_solve < $1 > ${1%.*}.log & tail -f ${1%.*}.log

