--- lanmap/src/Makefile.in	2006-03-07 15:44:32.000000000 +0100
+++ lanmap/src/Makefile.in.new	2008-12-02 16:08:13.000000000 +0100
@@ -2,8 +2,8 @@
 # $Id$
 
 # complation
-CFLAGS = -W -Wall -Wno-unused -DLINUX -DLANMAP_DATADIR=$(LANMAP_DATADIR)
-LDFLAGS = -lpcap -lm
+CFLAGS += -DLINUX -DLANMAP_DATADIR=$(LANMAP_DATADIR)
+LDFLAGS += -lpcap -lm
 CFLAGS_DEBUG = -D_DEBUG -ggdb
 LDFLAGS_DEBUG = -pg
 BINARY = lanmap
