--- msms/i86Linux2/Makefile	2007-10-03 21:06:31.000000000 +0200
+++ msms/i86Linux2/Makefile.new	2008-12-18 11:51:36.000000000 +0100
@@ -31,7 +31,7 @@
 	$(CC) $(CFLAGS) -static -static-libgcc $(OBJECTS) -o msms.${ARCHOSV}.$(VERSION).$(RELEASE).staticgcc $(LIBS)
 
 msms  : $(HEADER) $(OBJECTS)
-	$(CC) $(CFLAGS) $(OBJECTS) -o msms.${ARCHOSV}.$(VERSION).$(RELEASE) $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(OBJECTS) -o msms.${ARCHOSV}.$(VERSION).$(RELEASE) $(LIBS) 
 
 main.o : main.c
 	sed -e 's/VERSION = "";/VERSION = "$(VERSION).$(RELEASE)";/' $(VPATH)/main.c >! $(VPATH)/main.vers.c
--- msms/linux-x86_64/Makefile	2007-10-03 21:06:31.000000000 +0200
+++ msms/linux-x86_64/Makefile.new	2008-12-18 11:51:36.000000000 +0100
@@ -31,7 +31,7 @@
 	$(CC) $(CFLAGS) -static -static-libgcc $(OBJECTS) -o msms.${ARCHOSV}.$(VERSION).$(RELEASE).staticgcc $(LIBS)
 
 msms  : $(HEADER) $(OBJECTS)
-	$(CC) $(CFLAGS) $(OBJECTS) -o msms.${ARCHOSV}.$(VERSION).$(RELEASE) $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(OBJECTS) -o msms.${ARCHOSV}.$(VERSION).$(RELEASE) $(LIBS) 
 
 main.o : main.c
 	sed -e 's/VERSION = "";/VERSION = "$(VERSION).$(RELEASE)";/' $(VPATH)/main.c >! $(VPATH)/main.vers.c
