# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.1

EAPI="3"

PYTHON_DEPEND="2"
SUPPORT_PYTHON_ABIS="1"
RESTRICT_PYTHON_ABIS="3.*"

inherit distutils

DESCRIPTION="A Python module for retrieving and setting network device settings"
HOMEPAGE="http://pypi.python.org/pypi/pynetinfo/"
SRC_URI="mirror://pypi/p/pynetinfo/Pynetinfo-${PV}.tar.gz"

LICENSE="GPL-2"
KEYWORDS="amd64 x86"
SLOT="0"
IUSE=""

S="${WORKDIR}"/Pynetinfo-${PV}
