# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.1

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils python

DESCRIPTION="A Python module for retrieving and setting network device settings"
HOMEPAGE="http://pypi.python.org/pypi/pynetinfo/0.2.3"
SRC_URI="http://pypi.python.org/packages/source/p/pynetinfo/Pynetinfo-${PV}.tar.gz"

LICENSE=""
KEYWORDS="amd64 x86"
SLOT="0"
IUSE=""


PYTHON_MODNAME=""

src_unpack() {
	unpack "${A}"
	cd "Pynetinfo-${PV}" || die
}

src_compile() {
	cd "Pynetinfo-${PV}" || die
	distutils_src_compile
}

src_install() {
	#cd "${P}" # and this...
	cd "Pynetinfo-${PV}" || die
	distutils_src_install
}