# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.1

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="IP subnet calculator"
HOMEPAGE="http://dev.tehmaze.com/projects/ipcalc"
SRC_URI="http://pypi.python.org/packages/source/i/ipcalc/${P}.tar.gz"

LICENSE=""
KEYWORDS="amd64 x86"
SLOT="0"
IUSE=""


PYTHON_MODNAME=""

