--- Aqva/Aqva4.4.pro	2008-09-19 12:31:02.000000000 +0200
+++ Aqva/Aqva4.4.pro.new	2008-12-21 20:59:07.955994506 +0100
@@ -52,11 +52,11 @@
 		Algorithm/*.ui \
 		Tools/*.ui \
 
-ALMOST = ../contrib/almost-1.0.3/
+ALMOST = /usr/
 
 INCPATH += 	$$ALMOST \
-		$$ALMOST/include/almost  \
-		/Developer/SDKs/MacOSX10.4u.sdk/System/Library/Frameworks/GLUT.framework/Versions/A/Headers/
+		/usr/include/almost \
+		.
 
 
 mac {
@@ -72,7 +72,7 @@
 
 }
 
-LIBS          += -L$$ALMOST/src/lib/ -lAlm  -L$$ALMOST/src/forcefield -lnbimpl -L$$ALMOST/src/tinyxml -ltxml  -L$$ALMOST/src/lib/modules/ -lshx  -lbz2 -lz 
+LIBS          += -L/usr/lib/ -lAlm  -L/usr/include/almost/forcefield -lnbimpl -L/usr/include/almost/tinyxml -L/usr/include/almost/modules -ltxml -lshx  -lbz2 -lz -L/mnt/tmpfs/aqvahome/contrib/almost-1.0.3/
 
 QMAKE_CXXFLAGS +=-DALM_AQVA 
 
