#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

start() {
	ebegin "Starting AmavisVTd"
	start-stop-daemon --start --exec /usr/bin/amavisvtd \
		--user ${AMAVISVT_USER:=nobody} --group=${AMAVISVT_GROUP:=nobody} \
		--make-pidfile --pidfile /run/amavisvtd.pid \
		--background -- ${AMAVISVT_ARGS}
	eend $*
}

stop() {
	ebegin "Stopping AmavisVTd"
	start-stop-daemon --stop --exec /usr/bin/amavisvtd \
		--pidfile /run/amavisvtd.pid
	eend $*
}
